const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const config = window.APP_CONFIG || {};
const configured = /^https:\/\/.+\.supabase\.co$/.test(config.supabaseUrl || '') && !!config.supabaseAnonKey;
const money = n => new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n);
const state = {
  demo: true,
  members:[{name:'Matías',value:156800,color:'#ec755d'},{name:'Giselle',value:121400,color:'#f2cf78'},{name:'Iara',value:89300,color:'#6c9e89'},{name:'Milagros',value:61150,color:'#b7c7d4'}],
  movements:[
    {merchant:'Coto',meta:'Hoy · Matías · Comida',amount:38500,icon:'▦',date:new Date().toISOString().slice(0,10)},
    {merchant:'Edenor',meta:'Ayer · Giselle · Servicios',amount:24780,icon:'ϟ',date:new Date(Date.now()-864e5).toISOString().slice(0,10)},
    {merchant:'Farmacity',meta:'2 oct · Iara · Salud',amount:12300,icon:'+',date:new Date(Date.now()-5*864e5).toISOString().slice(0,10)},
    {merchant:'YPF',meta:'1 oct · Matías · Transporte',amount:18900,icon:'⌁',date:new Date(Date.now()-12*864e5).toISOString().slice(0,10)}]
};
const rules=[
  {test:/\b(coto|supermercado|pampero)\b/i,cat:'Comida',sub:'Supermercado'},
  {test:/^(ml|mercado\s*libre)$/i,cat:'Otros',sub:'Otros',display:'ML'},
  {test:/edenor|edesur|metrogas|aysa|internet|movistar|personal/i,cat:'Servicios',sub:'Servicios del hogar'},
  {test:/flow|cablevision|fibertel/i,cat:'Servicios',sub:'Internet'},
  {test:/farm|doctor|hospital|salud/i,cat:'Salud',sub:'Farmacia'},
  {test:/ypf|shell|axion|uber|cabify|sube/i,cat:'Transporte',sub:'Movilidad'},
  {test:/colegio|escuela|librer/i,cat:'Educación',sub:'Educación'}];
const aliases=[{canonical:'ML',terms:['ml','mercado libre','mercadolibre']},{canonical:'Flow',terms:['flow','cablevision','cable visión','fibertel']},{canonical:'Disney+',terms:['disney','disney plus','disnet']},{canonical:'YouTube Premium',terms:['youtube premium','youtube']},{canonical:'Mercado Pago',terms:['mp','mercado pago','mercadopago']}];
const normalize=text=>text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
function distance(a,b){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old}}return row[b.length]}
function resolveAlias(value){const clean=normalize(value);if(clean.length<2)return null;let best=null;for(const item of aliases){for(const term of item.terms){const target=normalize(term),score=distance(clean,target),allowed=Math.max(1,Math.floor(target.length*.18));if(clean===target||score<=allowed){if(!best||score<best.score)best={...item,score}}}}return best}
function resolveMerchant(value){const clean=normalize(value),alias=resolveAlias(value);if(clean.length<2)return {alias};let best=null;for(const provider of state.remote?.providers||[]){for(const term of [provider.nombre,provider.nombre_normalizado].filter(Boolean)){const target=normalize(term),score=distance(clean,target),allowed=Math.max(1,Math.floor(target.length*.16)),aliasMatches=alias?.terms.some(t=>normalize(t)===target);if(clean===target||score<=allowed||aliasMatches){if(!best||score<best.score)best={provider,score}}}}return {alias,provider:best?.provider,display:alias?.canonical||best?.provider?.nombre}}
function updateSubcategoryOptions(preferred=''){const category=$('#category').value,subs=state.remote?.subcategories.filter(s=>s.categoria_id===category)||[];$('#subcategory').innerHTML='<option value="">Elegir…</option>'+subs.map(s=>`<option value="${s.id}">${s.nombre}</option>`).join('');const match=subs.find(s=>normalize(s.nombre)===normalize(preferred));if(match)$('#subcategory').value=match.id}

function toast(text){const el=$('#toast'); el.textContent=text; el.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function supabase(path, options={}){return fetch(`${config.supabaseUrl}${path}`,{...options,headers:{apikey:config.supabaseAnonKey,Authorization:`Bearer ${localStorage.getItem('gf_token') || config.supabaseAnonKey}`,'Content-Type':'application/json',...(options.headers||{})}}).then(async r=>{const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.msg||body.message||body.error_description||'No se pudo completar la operación');return body})}
async function restoreSession(){const refresh=localStorage.getItem('gf_refresh');if(!refresh||!configured)return;try{let user;try{user=await supabase('/auth/v1/user')}catch{const renewed=await supabase('/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{Authorization:`Bearer ${config.supabaseAnonKey}`},body:JSON.stringify({refresh_token:refresh})});localStorage.setItem('gf_token',renewed.access_token);localStorage.setItem('gf_refresh',renewed.refresh_token);user=renewed.user}const label=await loadRemoteData(user);openApp(label)}catch{localStorage.removeItem('gf_token');localStorage.removeItem('gf_refresh')}}
async function loadRemoteData(user){
  const [members,categories,subcategories,providers,expenses]=await Promise.all([
    supabase('/rest/v1/miembros?select=*&activo=eq.true'),supabase('/rest/v1/categorias?select=*&activo=eq.true'),supabase('/rest/v1/subcategorias?select=*&activo=eq.true'),supabase('/rest/v1/proveedores?select=*&activo=eq.true'),supabase('/rest/v1/gastos?select=*&order=fecha.desc,created_at.desc&limit=1000')
  ]);
  state.remote={members,categories,subcategories,providers};
  const current=members.find(m=>m.auth_user_id===user?.id);state.familyId=current?.familia_id;state.currentMember=current;
  $('#category').innerHTML=categories.map(c=>`<option value="${c.id}">${c.nombre}</option>`).join('');
  $('#paidBy').innerHTML=members.map(m=>`<option value="${m.id}">${m.nombre}</option>`).join('');
  updateSubcategoryOptions();
  const month=new Date().toISOString().slice(0,7), currentExpenses=expenses.filter(g=>String(g.fecha).startsWith(month));
  state.members=members.map((m,i)=>({id:m.id,name:m.nombre,value:currentExpenses.filter(g=>g.pagado_por_id===m.id).reduce((s,g)=>s+Number(g.monto),0),color:['#ec755d','#f2cf78','#6c9e89','#b7c7d4'][i%4]}));
  state.movements=expenses.map(g=>({id:g.id,createdBy:g.creado_por_id,payerId:g.pagado_por_id,merchant:providers.find(p=>p.id===g.proveedor_id)?.nombre||g.descripcion||'Gasto',meta:`${g.fecha} · ${members.find(m=>m.id===g.pagado_por_id)?.nombre||''} · ${categories.find(c=>c.id===g.categoria_id)?.nombre||''}`,amount:Number(g.monto),icon:'▦',date:g.fecha}));
  return current?.alias||current?.nombre?.split(' ')[0]||user?.email?.split('@')[0]||'Familia';
}
function openApp(name='Mati'){state.demo=!localStorage.getItem('gf_token');state.currentName=name;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=name;$('#profileName').textContent=name;$('#profileButton').textContent=name[0].toUpperCase();$('#profileAvatar').textContent=name[0].toUpperCase();render()}
function render(){
  const total=state.members.reduce((a,b)=>a+b.value,0), max=Math.max(1,...state.members.map(m=>m.value));
  const lookup={mati:'matías',gi:'giselle',mili:'milagros'}, key=(state.currentName||'Mati').toLowerCase(), wanted=lookup[key]||key;
  const personal=state.members.find(m=>m.name.toLowerCase().startsWith(wanted))||state.members[0];
  $('#personalTotal').textContent=money(personal?.value||0);$('#monthTotal').textContent=money(total);$('#movementCount').textContent=`${state.movements.length} movimientos cargados`;
  $('#chart').innerHTML=state.members.map(m=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(12,m.value/max*90)}%;background:${m.color}" data-value="${money(m.value)}"></div></div>`).join('');
  $('#legend').innerHTML=state.members.map(m=>`<span><i style="background:${m.color}"></i>${m.name}</span>`).join('');
  $('#movements').innerHTML=state.movements.slice(0,4).map(m=>`<div class="movement"><span class="movement-icon">${m.icon}</span><div><p>${m.merchant}</p><small>${m.meta}</small></div><strong>− ${money(m.amount)}<small>Confirmado</small></strong></div>`).join('');
  renderAllMovements();renderTimeline(document.querySelector('.period-tabs .active')?.dataset.period||'month');
}
function movementMarkup(m){const canDelete=state.demo||state.currentMember?.rol==='admin'||m.createdBy===state.currentMember?.id;return `<div class="movement"><span class="movement-icon">${m.icon}</span><div><p>${m.merchant}</p><small>${m.meta}</small></div><strong>− ${money(m.amount)}<small>Confirmado</small></strong>${canDelete?`<button class="delete-expense" data-delete="${m.id}" aria-label="Eliminar ${m.merchant}">×</button>`:''}</div>`}
function renderAllMovements(filter=''){state.movements.forEach((m,i)=>{if(!m.id)m.id=`demo-${i}`});const term=filter.trim().toLowerCase(),items=state.movements.filter(m=>`${m.merchant} ${m.meta}`.toLowerCase().includes(term));$('#allMovements').innerHTML=items.length?items.map(movementMarkup).join(''):'<div class="empty-state">No encontramos movimientos con esa búsqueda.</div>'}
async function deleteExpense(id){const item=state.movements.find(m=>String(m.id)===String(id));if(!item||!confirm(`¿Eliminar el gasto de ${item.merchant} por ${money(item.amount)}?`))return;try{if(!state.demo)await supabase(`/rest/v1/gastos?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});state.movements=state.movements.filter(m=>String(m.id)!==String(id));const payer=state.members.find(m=>m.name===item.meta.split(' · ')[1]||m.id===item.payerId);if(payer)payer.value=Math.max(0,payer.value-item.amount);render();toast('Gasto eliminado')}catch(err){toast(`No se pudo eliminar: ${err.message}`)}}
function timelineData(period){const now=new Date(),items=state.movements.map(m=>({...m,d:new Date(`${m.date||new Date().toISOString().slice(0,10)}T12:00:00`)}));if(period==='week'){return Array.from({length:7},(_,i)=>{const d=new Date(now);d.setDate(now.getDate()-6+i);const key=d.toISOString().slice(0,10);return {label:new Intl.DateTimeFormat('es-AR',{weekday:'short'}).format(d),value:items.filter(m=>m.date===key).reduce((s,m)=>s+m.amount,0)}})}if(period==='year'){return Array.from({length:12},(_,i)=>({label:new Intl.DateTimeFormat('es-AR',{month:'short'}).format(new Date(now.getFullYear(),i,1)),value:items.filter(m=>m.d.getFullYear()===now.getFullYear()&&m.d.getMonth()===i).reduce((s,m)=>s+m.amount,0)}))}return Array.from({length:5},(_,i)=>({label:`Sem ${i+1}`,value:items.filter(m=>m.d.getFullYear()===now.getFullYear()&&m.d.getMonth()===now.getMonth()&&Math.min(4,Math.floor((m.d.getDate()-1)/7))===i).reduce((s,m)=>s+m.amount,0)}))}
function renderTimeline(period){const data=timelineData(period),max=Math.max(1,...data.map(d=>d.value)),total=data.reduce((s,d)=>s+d.value,0);$('#summaryTotal').textContent=`Total del período: ${money(total)}`;$('#timelineChart').innerHTML=data.map(d=>`<div class="time-column"><span>${d.value?money(d.value):''}</span><i style="height:${Math.max(d.value?8:2,d.value/max*100)}%"></i><small>${d.label}</small></div>`).join('')}
function showView(id){$$('.app-section').forEach(v=>v.classList.toggle('hidden',v.id!==id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='summaryView')renderTimeline(document.querySelector('.period-tabs .active')?.dataset.period||'month')}
$('#todayLabel').textContent=new Intl.DateTimeFormat('es-AR',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase();
$('#expenseDate').value=new Date().toISOString().slice(0,10);
$('#configHint').textContent=configured?'Conexión segura lista.':'Modo demo disponible · falta config.js para conectar Supabase.';
function showLoginForm(){const intro=$('#loginIntro');intro.classList.add('launching');setTimeout(()=>{$('#loginView').classList.add('form-open');$('#loginPanel').classList.remove('login-panel-hidden');setTimeout(()=>$('#email').focus(),350)},520)}
$('#startLogin').onclick=showLoginForm;
$('#backToIntro').onclick=()=>{$('#loginView').classList.remove('form-open');$('#loginPanel').classList.add('login-panel-hidden');$('#loginIntro').classList.remove('launching')};
$('#showPassword').onclick=()=>{const p=$('#password');p.type=p.type==='password'?'text':'password'};
$('#movementSearch').oninput=e=>renderAllMovements(e.target.value);
$('#allMovements').onclick=e=>{const button=e.target.closest('[data-delete]');if(button)deleteExpense(button.dataset.delete)};
$$('.period-tabs button').forEach(button=>button.onclick=()=>{$$('.period-tabs button').forEach(b=>b.classList.remove('active'));button.classList.add('active');renderTimeline(button.dataset.period)});
$$('.bottom-nav button').forEach(button=>button.onclick=()=>showView(button.dataset.view));
$('#profileButton').onclick=()=>showView('profileView');
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!configured)return toast('Falta configurar la URL y la clave pública de Supabase.');const btn=e.submitter;btn.disabled=true;try{const data=await supabase('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});localStorage.setItem('gf_token',data.access_token);localStorage.setItem('gf_refresh',data.refresh_token);const label=await loadRemoteData(data.user);openApp(label)}catch(err){localStorage.removeItem('gf_token');toast(err.message)}finally{btn.disabled=false}};
function toggleModal(show){$('#expenseModal').classList.toggle('hidden',!show);document.body.style.overflow=show?'hidden':'';if(show)setTimeout(()=>$('#amount').focus(),100)}
$('#addExpenseButton').onclick=()=>toggleModal(true);$$('[data-close]').forEach(b=>b.onclick=()=>toggleModal(false));
$('#amount').addEventListener('input',e=>{const digits=e.target.value.replace(/\D/g,'').replace(/^0+(?=\d)/,'');e.target.value=digits?new Intl.NumberFormat('es-AR').format(Number(digits)):''});
$('#category').addEventListener('change',()=>updateSubcategoryOptions());
$('#merchant').addEventListener('input',e=>{const resolved=resolveMerchant(e.target.value),provider=resolved.provider,providerCategory=state.remote?.categories.find(c=>c.id===provider?.categoria_default_id),providerSubcategory=state.remote?.subcategories.find(s=>s.id===provider?.subcategoria_default_id),search=resolved.alias?.canonical||e.target.value,rule=rules.find(r=>r.test.test(search)),cat=providerCategory?.nombre||rule?.cat,sub=providerSubcategory?.nombre||rule?.sub;$('#suggestion').classList.toggle('hidden',!cat);$('#rememberProviderWrap').classList.add('hidden');state.isNewProvider=false;state.suggestedProvider=provider||null;state.merchantAlias=resolved.alias;state.suggestedRule=rule||null;if(cat){$('#suggestionText').textContent=`${cat}${sub?` · ${sub}`:''}`;$('#category').value=providerCategory?.id||state.remote?.categories.find(c=>c.nombre===cat)?.id||cat;updateSubcategoryOptions(sub||'')}});
$('#merchant').addEventListener('blur',e=>{const resolved=resolveMerchant(e.target.value);if(resolved.display)e.target.value=resolved.display;if(!resolved.provider&&!state.suggestedRule&&normalize(e.target.value).length>1){state.isNewProvider=true;$('#suggestion').classList.remove('hidden');$('#suggestionText').textContent='Proveedor nuevo · Elegí su categoría';$('#categoryFields').classList.remove('hidden');$('#rememberProviderWrap').classList.remove('hidden');updateSubcategoryOptions()}});
$('#editCategory').onclick=()=>{$('#categoryFields').classList.toggle('hidden');$('#category').focus()};
$('#expenseForm').onsubmit=async e=>{e.preventDefault();const amount=Number($('#amount').value.replace(/\./g,'').replace(',','.'));if(!amount||amount<=0)return toast('Ingresá un monto válido.');const merchant=$('#merchant').value.trim();const scope=$('input[name="scope"]:checked').value;const category=$('#category').value;const payer=$('#paidBy').value;let categoryName=category,payerName=payer;
  let savedId=state.demo?`demo-${Date.now()}`:null;if(configured&&!state.demo){try{const cat=state.remote.categories.find(c=>c.id===category),sub=state.remote.subcategories.find(s=>s.id===$('#subcategory').value),remember=$('#rememberProvider').checked;let provider=state.suggestedProvider||resolveMerchant(merchant).provider;if(state.isNewProvider&&!sub)return toast('Elegí una subcategoría para el comercio nuevo.');if(state.isNewProvider&&remember){const created=await supabase('/rest/v1/proveedores',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({familia_id:state.familyId,nombre:merchant,nombre_normalizado:normalize(merchant),categoria_default_id:category,subcategoria_default_id:sub?.id||null})});provider=created?.[0];if(provider)state.remote.providers.push(provider)}categoryName=cat?.nombre||'';payerName=state.remote.members.find(m=>m.id===payer)?.nombre||'';const saved=await supabase('/rest/v1/gastos',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({monto:amount,descripcion:merchant,fecha:$('#expenseDate').value,ambito:scope.toLowerCase(),pagado_por_id:payer,categoria_id:category,subcategoria_id:sub?.id||null,proveedor_id:provider?.id||null,origen:'manual',clasificacion:provider||sub?'regla':'manual'})});savedId=saved?.[0]?.id}catch(err){return toast(`No se guardó: ${err.message}`)}}
  state.movements.unshift({id:savedId,createdBy:state.currentMember?.id,payerId:payer,merchant,meta:`Hoy · ${payerName} · ${categoryName}`,amount,icon:'▦',date:$('#expenseDate').value});const member=state.members.find(m=>m.name===payerName);if(member)member.value+=amount;render();toggleModal(false);e.target.reset();state.isNewProvider=false;state.suggestedProvider=null;$('#expenseDate').value=new Date().toISOString().slice(0,10);$('#suggestion').classList.add('hidden');$('#categoryFields').classList.add('hidden');$('#rememberProviderWrap').classList.add('hidden');toast('Gasto guardado correctamente');
};
$('#logoutButton').onclick=()=>{if(state.demo)return location.reload();localStorage.removeItem('gf_token');localStorage.removeItem('gf_refresh');location.reload()};
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
restoreSession();
